// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as windows$0 from "../golang.org/x/sys/windows/models.js";

export class UserWindow {
    "IsForeground": boolean;
    "LastActive": number;
    "Hwnd": windows$0.HWND;
    "Caption": string;
    "IconBase64": string;

    /** Creates a new UserWindow instance. */
    constructor($$source: Partial<UserWindow> = {}) {
        if (!("IsForeground" in $$source)) {
            this["IsForeground"] = false;
        }
        if (!("LastActive" in $$source)) {
            this["LastActive"] = 0;
        }
        if (!("Hwnd" in $$source)) {
            this["Hwnd"] = windows$0.HWND.$zero;
        }
        if (!("Caption" in $$source)) {
            this["Caption"] = "";
        }
        if (!("IconBase64" in $$source)) {
            this["IconBase64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserWindow instance from a string or object.
     */
    static createFrom($$source: any = {}): UserWindow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserWindow($$parsedSource as Partial<UserWindow>);
    }
}
