// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as windows$0 from "../../../../../golang.org/x/sys/windows/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../../tabswitcher/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "activateWindow": windows$0.HWND;
            "systemKeyPressed": string;
            "userWindowsChanged": main$0.UserWindow[];
        }
    }
}
